### ISSUE TITLE
wrong arg in helmchart for leader-election 

### ISSUE THREAD

**Issue by stefffhem** [redhat-cop/keepalived-operator#56]
I found an issue regarding helmchart keepalived-operator-v1.0.0.tgz. There is a wrong arg inside the Chart-Template :

keepalived-operator/templates/manager.yaml

Does not work:

```
 containers:
      - command:
        - /manager
        args:
        - --enable-leader-election
```
Fix to working arg:

```
containers:
      - command:
        - /manager
        args:
        - --leader-elect
